# Generated by Django 2.1.7 on 2019-03-14 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
