# Generated by Django 2.1.7 on 2019-03-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190314_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
