# Generated by Django 2.1.7 on 2019-03-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190326_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
