# Generated by Django 2.1.7 on 2019-03-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarclaysDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Barclays Daily',
                'verbose_name_plural': 'Barclays Dailies',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Identifier',
                'verbose_name_plural': 'Identifiers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='barclaysdaily',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Day'),
        ),
        migrations.AddField(
            model_name='barclaysdaily',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='barclaysdaily',
            unique_together={('date', 'identifier')},
        ),
    ]
