# Generated by Django 2.1.7 on 2019-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barclaysdaily',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='barclaysdaily',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
