# Generated by Django 2.1.7 on 2019-03-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20190326_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bihldaily',
            options={'ordering': ['-date'], 'verbose_name': 'Bihl Daily', 'verbose_name_plural': 'Bihl Dailies'},
        ),
    ]
